risk_keywords = [
    {"keyword": "phishing", "weight": 5},
    {"keyword": "phishing link", "weight": 5},
    {"keyword": "dolandırıcılık", "weight": 5},
    {"keyword": "sahte site", "weight": 5},
    {"keyword": "fake giveaway", "weight": 5},
    {"keyword": "ödeme linki", "weight": 5},
    {"keyword": "ödeme yapın", "weight": 5},
    {"keyword": "kart bilgisi", "weight": 5},
    {"keyword": "kimlik doğrulama", "weight": 5},
    {"keyword": "verify your identity", "weight": 5},
    {"keyword": "credit card scam", "weight": 5},
    {"keyword": "login trap", "weight": 5},
    {"keyword": "hesap çalma", "weight": 5},
    {"keyword": "account hack", "weight": 5},
    {"keyword": "fake checkout", "weight": 5},
    {"keyword": "sahte ödeme", "weight": 5},
    {"keyword": "ödül kazandınız", "weight": 4},
    {"keyword": "hediye kazandınız", "weight": 4},
    {"keyword": "you won", "weight": 4},
    {"keyword": "kazandınız", "weight": 4},
    {"keyword": "çekiliş", "weight": 4},
    {"keyword": "click here", "weight": 4},
    {"keyword": "linke tıklayın", "weight": 4},
    {"keyword": "apk indir", "weight": 4},
    {"keyword": "modlu apk", "weight": 4},
    {"keyword": "mobile cheat", "weight": 4},
    {"keyword": "game cheat", "weight": 4},
    {"keyword": "steam kodu", "weight": 4},
    {"keyword": "epic games hediyesi", "weight": 4},
    {"keyword": "free skin", "weight": 4},
    {"keyword": "skin satışı", "weight": 4},
    {"keyword": "premium üyelik", "weight": 4},
    {"keyword": "premium membership", "weight": 4},
    {"keyword": "bedava elmas", "weight": 4},
    {"keyword": "unlimited coins", "weight": 4},
    {"keyword": "ücretsiz oyun", "weight": 3},
    {"keyword": "free game", "weight": 3},
    {"keyword": "gizli kampanya", "weight": 3},
    {"keyword": "indirim tuzağı", "weight": 3},
    {"keyword": "fake product", "weight": 3},
    {"keyword": "sahte ürün", "weight": 3},
    {"keyword": "oyun hesabı", "weight": 3},
    {"keyword": "game account", "weight": 3},
    {"keyword": "oyun kodu", "weight": 3},
    {"keyword": "steam key", "weight": 3},
    {"keyword": "epic giveaway", "weight": 3},
    {"keyword": "free download", "weight": 3},
    {"keyword": "ücretsiz indir", "weight": 3},
    {"keyword": "indirimli fiyat", "weight": 2},
    {"keyword": "discounted price", "weight": 2},
    {"keyword": "buy now", "weight": 2},
    {"keyword": "hemen satın al", "weight": 2},
    {"keyword": "şimdi al", "weight": 2},
    {"keyword": "satın almak için tıklayın", "weight": 2},
    {"keyword": "make payment", "weight": 2},
    {"keyword": "pay with card", "weight": 2},
    {"keyword": "kartla ödeme", "weight": 2},
    {"keyword": "kredi kartı ile satın al", "weight": 2},
    {"keyword": "sınırlı süreli teklif", "weight": 2},
    {"keyword": "limited time offer", "weight": 2},
    {"keyword": "garantili satış", "weight": 2},
    {"keyword": "secure payment", "weight": 2},
    {"keyword": "2. el", "weight": 1},
    {"keyword": "ikinci el", "weight": 1},
    {"keyword": "used item", "weight": 1},
    {"keyword": "second hand", "weight": 1},
    {"keyword": "bonus kazan", "weight": 3},
    {"keyword": "ödeme onayı", "weight": 4},
    {"keyword": "şifre girin", "weight": 4},
    {"keyword": "şifrenizi doğrulayın", "weight": 5},
    {"keyword": "hesap doğrulama", "weight": 5},
    {"keyword": "giriş yapın", "weight": 4},
    {"keyword": "hesabınıza erişin", "weight": 4},
    {"keyword": "hesap kilitlendi", "weight": 5},
    {"keyword": "hesap askıya alındı", "weight": 5},
    {"keyword": "hesap güvenliği", "weight": 3},
    {"keyword": "güvenlik uyarısı", "weight": 4},
    {"keyword": "şüpheli işlem", "weight": 4},
    {"keyword": "şüpheli etkinlik", "weight": 4},
    {"keyword": "kimlik hırsızlığı", "weight": 5},
    {"keyword": "identity theft", "weight": 5},
    {"keyword": "malicious site", "weight": 5},
    {"keyword": "fake login", "weight": 5},
    {"keyword": "fake invoice", "weight": 4},
    {"keyword": "invoice scam", "weight": 4},
    {"keyword": "payment required", "weight": 4},
    {"keyword": "urgent action", "weight": 4},
    {"keyword": "act now", "weight": 3},
    {"keyword": "limited access", "weight": 3},
    {"keyword": "account suspended", "weight": 5},
    {"keyword": "verify now", "weight": 4},
    {"keyword": "update credentials", "weight": 4},
    {"keyword": "security alert", "weight": 4},
    {"keyword": "unauthorized access", "weight": 5},
    {"keyword": "confirm payment", "weight": 4},
    {"keyword": "billing issue", "weight": 3},
    {"keyword": "urgent verification", "weight": 5}
]